# Generated by Django 3.2.7 on 2021-10-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChemHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='density_at_mp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='density_at_rt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='density_at_stp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
