# Generated by Django 3.2.7 on 2021-10-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChemHub', '0002_auto_20211020_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='density',
        ),
    ]
