# Generated by Django 3.2.7 on 2021-10-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChemHub', '0003_remove_element_density'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='critical_point',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='heat_capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='ox_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='triple_point',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
