# Generated by Django 3.2.7 on 2021-10-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChemHub', '0004_auto_20211020_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='sublimation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='boiling',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='melting',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
