# Generated by Django 3.2.7 on 2021-10-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CookieBook', '0002_auto_20211022_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img_final',
            field=models.FileField(blank=True, null=True, upload_to='static/Images/Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='img_initial',
            field=models.FileField(blank=True, null=True, upload_to='static/Images/Recipe'),
        ),
    ]
