# Generated by Django 3.2.6 on 2022-01-25 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0003_rename_usersettings_usersetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
