# Generated by Django 3.2.7 on 2021-10-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arcade', '0002_gameslist_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplodingKactiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=5)),
                ('name', models.CharField(blank=True, max_length=8)),
            ],
        ),
    ]
