# Generated by Django 3.2.7 on 2021-10-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arcade', '0003_explodingkactidata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExplodingKactiData',
            new_name='ExplodingKactiScore',
        ),
    ]
