# Generated by Django 3.2.7 on 2021-10-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arcade', '0004_rename_explodingkactidata_explodingkactiscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explodingkactiscore',
            name='score',
            field=models.IntegerField(),
        ),
    ]
